# Generated by Django 3.1.7 on 2021-05-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0002_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_board.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_board.author')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_board.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion_board.author')),
            ],
            options={
                'verbose_name_plural': 'replies',
            },
        ),
    ]
