# Generated by Django 3.1.7 on 2021-05-09 17:53

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0005_auto_20210503_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=400, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
    ]
