# Generated by Django 3.1.7 on 2021-05-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0006_auto_20210509_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
