# Generated by Django 3.1.7 on 2021-05-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0007_auto_20210518_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=None, max_length=400, unique=True),
        ),
    ]
